[2022-07-29 21:13:22,683] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-07-30T01:09:24.752685+00:00 [queued]>
[2022-07-29 21:13:22,763] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-07-30T01:09:24.752685+00:00 [queued]>
[2022-07-29 21:13:22,781] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 21:13:22,781] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-07-29 21:13:22,781] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 21:13:22,827] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): nse_files_move> on 2022-07-30 01:09:24.752685+00:00
[2022-07-29 21:13:22,830] {standard_task_runner.py:52} INFO - Started process 366341 to run task
[2022-07-29 21:13:22,835] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'nse_daily_data_load', 'nse_files_move', 'manual__2022-07-30T01:09:24.752685+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/nse_daily_load_stg.py', '--cfg-path', '/tmp/tmpafhaif0m', '--error-file', '/tmp/tmpb9p449u3']
[2022-07-29 21:13:22,835] {standard_task_runner.py:80} INFO - Job 77: Subtask nse_files_move
[2022-07-29 21:13:22,898] {task_command.py:369} INFO - Running <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-07-30T01:09:24.752685+00:00 [running]> on host osboxes
[2022-07-29 21:13:22,960] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=nse_daily_data_load
AIRFLOW_CTX_TASK_ID=nse_files_move
AIRFLOW_CTX_EXECUTION_DATE=2022-07-30T01:09:24.752685+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-30T01:09:24.752685+00:00
[2022-07-29 21:13:22,961] {logging_mixin.py:115} INFO - 2022-07-29
[2022-07-29 21:13:22,961] {logging_mixin.py:115} INFO - directory already available
[2022-07-29 21:13:22,961] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/archives_files/2022-07-29 target file location
[2022-07-29 21:13:22,961] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm29JUL2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm29JUL2022bhav.csv.zip' already exists
[2022-07-29 21:13:22,962] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm29JUL2022bhav.csv 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm29JUL2022bhav.csv' already exists
[2022-07-29 21:13:22,962] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm25JUL2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm25JUL2022bhav.csv.zip' already exists
[2022-07-29 21:13:22,962] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm28JUL2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm28JUL2022bhav.csv.zip' already exists
[2022-07-29 21:13:22,962] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm26JUL2022bhav.csv 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm26JUL2022bhav.csv' already exists
[2022-07-29 21:13:22,962] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm27JUL2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm27JUL2022bhav.csv.zip' already exists
[2022-07-29 21:13:22,962] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm27JUL2022bhav.csv 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm27JUL2022bhav.csv' already exists
[2022-07-29 21:13:22,962] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm25JUL2022bhav.csv 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm25JUL2022bhav.csv' already exists
[2022-07-29 21:13:22,962] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm26JUL2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm26JUL2022bhav.csv.zip' already exists
[2022-07-29 21:13:22,962] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm28JUL2022bhav.csv 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-29/cm28JUL2022bhav.csv' already exists
[2022-07-29 21:13:22,962] {python.py:173} INFO - Done. Returned value was: None
[2022-07-29 21:13:22,968] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=nse_daily_data_load, task_id=nse_files_move, execution_date=20220730T010924, start_date=20220730T011322, end_date=20220730T011322
[2022-07-29 21:13:23,034] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-29 21:13:23,092] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
