[2022-07-31 14:55:54,114] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-07-30T01:07:26.978376+00:00 [queued]>
[2022-07-31 14:55:54,123] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-07-30T01:07:26.978376+00:00 [queued]>
[2022-07-31 14:55:54,123] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 14:55:54,123] {taskinstance.py:1357} INFO - Starting attempt 5 of 5
[2022-07-31 14:55:54,123] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 14:55:54,179] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): nse_files_move> on 2022-07-30 01:07:26.978376+00:00
[2022-07-31 14:55:54,182] {standard_task_runner.py:52} INFO - Started process 832714 to run task
[2022-07-31 14:55:54,208] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'nse_daily_data_load', 'nse_files_move', 'manual__2022-07-30T01:07:26.978376+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/nse_daily_load_stg.py', '--cfg-path', '/tmp/tmph20m05lk', '--error-file', '/tmp/tmpzbzeporq']
[2022-07-31 14:55:54,220] {standard_task_runner.py:80} INFO - Job 113: Subtask nse_files_move
[2022-07-31 14:55:54,328] {task_command.py:369} INFO - Running <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-07-30T01:07:26.978376+00:00 [running]> on host osboxes
[2022-07-31 14:55:54,432] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=nse_daily_data_load
AIRFLOW_CTX_TASK_ID=nse_files_move
AIRFLOW_CTX_EXECUTION_DATE=2022-07-30T01:07:26.978376+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-30T01:07:26.978376+00:00
[2022-07-31 14:55:54,450] {logging_mixin.py:115} INFO - 2022-07-31
[2022-07-31 14:55:54,450] {logging_mixin.py:115} INFO - directory already available
[2022-07-31 14:55:54,450] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/archives_files/2022-07-31 target file location
[2022-07-31 14:55:54,451] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm29JUL2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-31/cm29JUL2022bhav.csv.zip' already exists
[2022-07-31 14:55:54,451] {python.py:173} INFO - Done. Returned value was: None
[2022-07-31 14:55:54,504] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=nse_daily_data_load, task_id=nse_files_move, execution_date=20220730T010726, start_date=20220731T185554, end_date=20220731T185554
[2022-07-31 14:55:54,666] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-31 14:55:54,846] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
