[2022-07-31 14:48:32,291] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-07-30T01:07:26.978376+00:00 [queued]>
[2022-07-31 14:48:32,309] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-07-30T01:07:26.978376+00:00 [queued]>
[2022-07-31 14:48:32,313] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 14:48:32,313] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-31 14:48:32,313] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 14:48:32,447] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): nse_files_move> on 2022-07-30 01:07:26.978376+00:00
[2022-07-31 14:48:32,451] {standard_task_runner.py:52} INFO - Started process 826741 to run task
[2022-07-31 14:48:32,460] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'nse_daily_data_load', 'nse_files_move', 'manual__2022-07-30T01:07:26.978376+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/nse_daily_load_stg.py', '--cfg-path', '/tmp/tmp3tsqesfk', '--error-file', '/tmp/tmp12l9ck6l']
[2022-07-31 14:48:32,461] {standard_task_runner.py:80} INFO - Job 102: Subtask nse_files_move
[2022-07-31 14:48:32,534] {task_command.py:369} INFO - Running <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-07-30T01:07:26.978376+00:00 [running]> on host osboxes
[2022-07-31 14:48:32,634] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=nse_daily_data_load
AIRFLOW_CTX_TASK_ID=nse_files_move
AIRFLOW_CTX_EXECUTION_DATE=2022-07-30T01:07:26.978376+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-30T01:07:26.978376+00:00
[2022-07-31 14:48:32,729] {logging_mixin.py:115} INFO - 2022-07-31
[2022-07-31 14:48:32,732] {logging_mixin.py:115} INFO - directory already available
[2022-07-31 14:48:32,735] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/archives_files/2022-07-31 target file location
[2022-07-31 14:48:32,736] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm29JUL2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-31/cm29JUL2022bhav.csv.zip' already exists
[2022-07-31 14:48:32,736] {python.py:173} INFO - Done. Returned value was: None
[2022-07-31 14:48:32,817] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=nse_daily_data_load, task_id=nse_files_move, execution_date=20220730T010726, start_date=20220731T184832, end_date=20220731T184832
[2022-07-31 14:48:33,010] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-31 14:48:33,265] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
