[2022-07-16 13:29:21,143] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Snowflake_automation.get_count manual__2022-07-16T15:19:48.207981+00:00 [queued]>
[2022-07-16 13:29:21,150] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Snowflake_automation.get_count manual__2022-07-16T15:19:48.207981+00:00 [queued]>
[2022-07-16 13:29:21,150] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 13:29:21,150] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2022-07-16 13:29:21,150] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 13:29:21,189] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_count> on 2022-07-16 15:19:48.207981+00:00
[2022-07-16 13:29:21,193] {standard_task_runner.py:52} INFO - Started process 123789 to run task
[2022-07-16 13:29:21,243] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Snowflake_automation', 'get_count', 'manual__2022-07-16T15:19:48.207981+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/test_0716.py', '--cfg-path', '/tmp/tmp8zy9_oqy', '--error-file', '/tmp/tmpl534c2ll']
[2022-07-16 13:29:21,246] {standard_task_runner.py:80} INFO - Job 15: Subtask get_count
[2022-07-16 13:29:21,441] {task_command.py:369} INFO - Running <TaskInstance: Snowflake_automation.get_count manual__2022-07-16T15:19:48.207981+00:00 [running]> on host osboxes
[2022-07-16 13:29:21,544] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=Snowflake_automation
AIRFLOW_CTX_TASK_ID=get_count
AIRFLOW_CTX_EXECUTION_DATE=2022-07-16T15:19:48.207981+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-16T15:19:48.207981+00:00
[2022-07-16 13:29:21,559] {base.py:68} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2022-07-16 13:29:21,564] {connection.py:257} INFO - Snowflake Connector for Python Version: 2.7.8, Python Version: 3.8.10, Platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.29
[2022-07-16 13:29:21,567] {connection.py:876} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-07-16 13:29:21,567] {connection.py:894} INFO - Setting use_openssl_only mode to False
[2022-07-16 13:29:22,754] {cursor.py:710} INFO - query: [select count(*) from EDW_PROD.EDW.Airflow_test_tab]
[2022-07-16 13:29:23,059] {cursor.py:734} INFO - query execution done
[2022-07-16 13:29:23,080] {connection.py:507} INFO - closed
[2022-07-16 13:29:23,239] {connection.py:510} INFO - No async queries seem to be running, deleting session
[2022-07-16 13:29:23,368] {test_0716.py:29} INFO - table row count2
[2022-07-16 13:29:23,372] {python.py:173} INFO - Done. Returned value was: None
[2022-07-16 13:29:23,387] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=Snowflake_automation, task_id=get_count, execution_date=20220716T151948, start_date=20220716T172921, end_date=20220716T172923
[2022-07-16 13:29:23,458] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-16 13:29:23,470] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
