[2022-08-09 11:11:00,711] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Stockdim_update.named_stg_tab_stg_l manual__2022-08-09T06:36:46.184026+00:00 [queued]>
[2022-08-09 11:11:00,720] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Stockdim_update.named_stg_tab_stg_l manual__2022-08-09T06:36:46.184026+00:00 [queued]>
[2022-08-09 11:11:00,720] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 11:11:00,721] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-09 11:11:00,721] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 11:11:00,787] {taskinstance.py:1377} INFO - Executing <Task(SnowflakeOperator): named_stg_tab_stg_l> on 2022-08-09 06:36:46.184026+00:00
[2022-08-09 11:11:00,791] {standard_task_runner.py:52} INFO - Started process 179526 to run task
[2022-08-09 11:11:00,796] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Stockdim_update', 'named_stg_tab_stg_l', 'manual__2022-08-09T06:36:46.184026+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/stock_scd2.py', '--cfg-path', '/tmp/tmpwqh2ss_5', '--error-file', '/tmp/tmpxacna4l7']
[2022-08-09 11:11:00,796] {standard_task_runner.py:80} INFO - Job 214: Subtask named_stg_tab_stg_l
[2022-08-09 11:11:00,872] {task_command.py:369} INFO - Running <TaskInstance: Stockdim_update.named_stg_tab_stg_l manual__2022-08-09T06:36:46.184026+00:00 [running]> on host osboxes
[2022-08-09 11:11:00,977] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=NSEstock
AIRFLOW_CTX_DAG_ID=Stockdim_update
AIRFLOW_CTX_TASK_ID=named_stg_tab_stg_l
AIRFLOW_CTX_EXECUTION_DATE=2022-08-09T06:36:46.184026+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-09T06:36:46.184026+00:00
[2022-08-09 11:11:00,977] {snowflake.py:118} INFO - Executing:  COPY into EDW_DEV.EDW.STOCK_DIM_STG select $1,$2,$3,$4,$5,metadata$filename from @EDW_DEV.EDW.NSE_DAILY_STG
 pattern= '.*ind_nifty.*'  file_format = 'EDW_DEV.EDW.NSE_SD_FMT_CSV' purge =true;
[2022-08-09 11:11:00,987] {base.py:68} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2022-08-09 11:11:00,990] {connection.py:257} INFO - Snowflake Connector for Python Version: 2.7.8, Python Version: 3.8.10, Platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.29
[2022-08-09 11:11:00,991] {connection.py:876} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-09 11:11:00,991] {connection.py:894} INFO - Setting use_openssl_only mode to False
[2022-08-09 11:11:03,058] {cursor.py:710} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-09 11:11:03,344] {cursor.py:734} INFO - query execution done
[2022-08-09 11:11:03,344] {snowflake.py:328} INFO - Running statement: COPY into EDW_DEV.EDW.STOCK_DIM_STG select $1,$2,$3,$4,$5,metadata$filename from @EDW_DEV.EDW.NSE_DAILY_STG
 pattern= '.*ind_nifty.*'  file_format = 'EDW_DEV.EDW.NSE_SD_FMT_CSV' purge =true;, parameters: None
[2022-08-09 11:11:03,349] {cursor.py:710} INFO - query: [COPY into EDW_DEV.EDW.STOCK_DIM_STG select $1,$2,$3,$4,$5,metadata$filename from...]
[2022-08-09 11:11:03,824] {cursor.py:734} INFO - query execution done
[2022-08-09 11:11:03,826] {connection.py:507} INFO - closed
[2022-08-09 11:11:03,870] {connection.py:510} INFO - No async queries seem to be running, deleting session
[2022-08-09 11:11:04,105] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/osboxes/.local/lib/python3.8/site-packages/airflow/providers/snowflake/operators/snowflake.py", line 120, in execute
    execution_info = hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/osboxes/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 332, in run
    cur.execute(sql_statement)
  File "/home/osboxes/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 799, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/osboxes/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 273, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/osboxes/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 328, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/osboxes/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 207, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01a62caf-0501-b49a-006e-0a830001731a: SQL compilation error:
syntax error line 1 at position 36 unexpected 'select'.
[2022-08-09 11:11:04,112] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=Stockdim_update, task_id=named_stg_tab_stg_l, execution_date=20220809T063646, start_date=20220809T151100, end_date=20220809T151104
[2022-08-09 11:11:04,187] {standard_task_runner.py:92} ERROR - Failed to execute job 214 for task named_stg_tab_stg_l (001003 (42000): 01a62caf-0501-b49a-006e-0a830001731a: SQL compilation error:
syntax error line 1 at position 36 unexpected 'select'.; 179526)
[2022-08-09 11:11:04,195] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-09 11:11:04,296] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
